### ISSUE TITLE
make v8 error

### ISSUE THREAD

**Issue by mrpre** [WebAssembly/wasm-c-api#79]
Seems `make v8-checkout` is successful while `make v8` not.    

`make v8-checkout`:   

```
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api# make v8-checkout
==== Checking out V8 branch-heads/7.4 ====
(cd v8/v8; git checkout -f master)
Previous HEAD position was 8a28642518 Version 7.4.288.28
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
(cd v8/v8; git pull)
Already up to date.
(cd v8/v8; git checkout branch-heads/7.4)
Note: checking out 'branch-heads/7.4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8a28642518 Version 7.4.288.28
(cd v8/v8; PATH=/root/v8/wasm-c-api/v8/depot_tools:/root/wasm/emsdk:/root/wasm/emsdk/fastcomp/emscripten:/root/wasm/emsdk/node/8.9.1_64bit/bin:/root/.wasmer/bin:/root/.wasmer/globals/wapm_packages/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/llvm/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/bin:/root/wavm/WAVM/bin:/root/bin gclient sync)
Running depot tools as root is sad.
Syncing projects: 100% (24/24), done.

WARNING: 'v8/third_party/perfetto' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.

WARNING: 'v8/third_party/protobuf' is no longer part of this client.
It is recommended that you manually remove it or use 'gclient sync -D' next time.
mkdir -p v8/v8/out.gn/x64.release
echo >v8/v8/out.gn/x64.release/version branch-heads/7.4
```  

`make v8`:  

```
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api# make v8
if ! grep wasm-v8-lowlevel v8/v8/BUILD.gn; then \
  cp v8/v8/BUILD.gn v8/v8/BUILD.gn.save; \
  cd v8/v8; \
  patch < ../../patch/0001-BUILD.gn-add-wasm-v8-lowlevel.patch; \
fi
patching file BUILD.gn
Hunk #1 succeeded at 1555 with fuzz 2 (offset 431 lines).
Hunk #2 succeeded at 1606 with fuzz 2 (offset 455 lines).
Hunk #3 succeeded at 1622 with fuzz 2 (offset 456 lines).
==== Building V8 branch-heads/7.4 x64.release ====
(cd v8/v8; PATH=/root/v8/wasm-c-api/v8/depot_tools:/root/wasm/emsdk:/root/wasm/emsdk/fastcomp/emscripten:/root/wasm/emsdk/node/8.9.1_64bit/bin:/root/.wasmer/bin:/root/.wasmer/globals/wapm_packages/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root/llvm/clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04/bin:/root/wavm/WAVM/bin:/root/bin tools/dev/v8gen.py x64.release -- is_component_build=false v8_static_library=true v8_monolithic=true v8_use_external_startup_data=false v8_enable_i18n_support=false use_custom_libcxx=false use_custom_libcxx_for_host=false)

Hint: You can raise verbosity (-vv) to see the output of failed commands.

Traceback (most recent call last):
  File "tools/dev/v8gen.py", line 307, in <module>
    sys.exit(gen.main())
  File "tools/dev/v8gen.py", line 301, in main
    return self._options.func()
  File "tools/dev/v8gen.py", line 169, in cmd_gen
    gn_outdir,
  File "tools/dev/v8gen.py", line 211, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/bin/python', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
Makefile:204: recipe for target 'v8-build' failed
make: *** [v8-build] Error 1
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api#
```

ENV:  
```
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api# python --version
Python 2.7.15rc1
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api#
```

```
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api# clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api# cat /etc/issue
Ubuntu 18.04.2 LTS \n \l

root@iZrj97ibqurmwnu9mj5htdZ:~/v8/wasm-c-api#
```

**Comment by rossberg** [comment]
Hm, can't reproduce that. It seems to be an issue with building V8 itself. Can you successfully build plain V8 when checked out as described on its homepage?

**Comment by PiotrSikora** [comment]
I suspect you have outdated/dirty v8 checkout.

Could you wipe it and start from scratch? i.e.
```
rm -rf v8/v8
make v8-checkout
make v8
```

**Comment by mrpre** [comment]
After following v8 build script, I find that `pkgconf` and `pkg-config` are needed. I think those deps should be added to README ro even installscript.

**Comment by jakobkummerow** [comment]
I'm pretty sure that V8 does not depend on pkgconf. Which build script did you follow?

**Comment by mrpre** [comment]
stack
```
pkg_config
build/config/linux/BUILD.gn         unclearly
build/config/linux/pkg-config.py    unclearly
tools/mb/mb.py                      unclearly
tools/dev/v8gen.py"                 line 211
```

**Comment by jakobkummerow** [comment]
Interesting, I've never noticed. I guess it's part of the "general development packages" that are assumed to be present on a machine used for development. Not sure where the best place is to document this...
